### ISSUE TITLE
Refactor CpanParser

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye-core#107]
There'll be breaking changes with newest `CpanParser`, which may break looking up Pods and their submodules.

TODO:

* fix tests
* add lookup method for modules;
* do tests runs with real projects on github;

**Comment by timgluz** [comment]
Check also version selectors.

Specifically check that the case "1.0.0" is handled as ">= 1.0.0", source: https://github.com/kraih/mojo/wiki/Installation-of-cpan-modules-by-cpanm-and-cpanfile

**Comment by reiz** [comment]
@timgluz That's the status on this? Is a PR for this ticket coming?

**Comment by timgluz** [comment]
Isn't that already merged.? It addee product.fetch_cpan method

**Comment by reiz** [comment]
Yes. It's added.
