### ISSUE TITLE
Add GithubComperator for Gemfile projects

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye-core#108]
re-use implementation of GithubComperators and add support for GIT and Github dependencies, which are hosted Github. 

here's the specification of Gemfile: https://bundler.io/v1.5/man/gemfile.5.html#GIT-git-

**Comment by timgluz** [comment]
Ready for review;

**Comment by reiz** [comment]
@timgluz looks good. I just merged. Tests are running.
