### ISSUE TITLE
Implemente parser for rebar

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#112]
Implement parser for Erlang rebar. See documentation here: https://github.com/rebar/rebar/wiki/Dependency-management

**Comment by timgluz** [comment]
Ok, should it consume packages hosted on Elixir's Mix? 

How critical is this task? Is it asked by client? 
I am asking it because, `rebar` is not deprecated in favor of `rebar3` - check readme in Github repo;

**Comment by timgluz** [comment]
Ok, seems there's not much differences between `rebar` and `rebar3` dependency format;

**Comment by reiz** [comment]
This has been merged and is part of versioneye-core.
