### ISSUE TITLE
Php dependencies ext-*

### ISSUE THREAD

**Issue by Geolim4** [versioneye/versioneye-core#40]
Hello,

It seems that php extensions dependencies aren't recognized, example here:
https://www.versioneye.com/php/phpfastcache:phpfastcache/5.0.7
The `ext-json` is perfectly legit and is recognized as "**unknown**" :)

Cheers,
Georges

**Comment by Geolim4** [comment]
Hello,
Here you go: https://getcomposer.org/doc/02-libraries.md#platform-packages

> ext-<name> allows you to require PHP extensions (includes core extensions). Versioning can be quite inconsistent here, so it's often a good idea to just set the constraint to *. An example of an extension package name is ext-gd.

**Comment by Geolim4** [comment]
It can be a valid php extension such as: json, gd, redis, etc.

**Comment by Geolim4** [comment]
@reiz Did you took the time to investigate on this ?
It can be pretty useful IMO !

**Comment by Geolim4** [comment]
@reiz  Up :)

**Comment by Geolim4** [comment]
Up !

**Comment by reiz** [comment]
@Geolim4 Yes. Currently going through my unread GitHub notifications. No arrived here :-)

**Comment by reiz** [comment]
@Geolim4 Are this extensions also published on Packagist.org? How can we get meta information about them?

**Comment by Geolim4** [comment]
@reiz 

Those extensions are php-core related, no composer related. They exist, that's it :)
It's some special cases that you need to handle case by case:

Php Json extension: http://php.net/manual/en/book.json.php

Have fun with your notifications :P

Cheers,
Georges

**Comment by reiz** [comment]
@Geolim4 But how should VersionEye know that they exist and what there newest version is? Is there any source there we can grep information about this libraries?

**Comment by Geolim4** [comment]
In fact those extensions does not have a specific version, they are directly handled by the php core. You just have to exclude any dependencies starting with "ext-*" from version checking.

**Comment by reiz** [comment]
@Geolim4 So you are saying all PHP dependencies starting with `ext-` are always up-to-date? Right?

**Comment by Geolim4** [comment]
Yes exactly, composer does not check any php extension version. So yes for
now (until future change?) consider php extensions as always stable :)

**Comment by reiz** [comment]
All right. I put that on the list. Should be implemented soon.

**Comment by reiz** [comment]
@Geolim4 I just set the newest version for those dependencies to `*`. See here: https://www.versioneye.com/php/phpfastcache:phpfastcache/6.0.1. Good enough?

**Comment by Geolim4** [comment]
@reiz Seems to be good, well done !
