### ISSUE TITLE
packages.config parsing doesn't seem to resolve the correct current version

### ISSUE THREAD

**Issue by Nysosis** [versioneye/versioneye-core#42]
Creating a project through uploading the attached [packages.config](https://github.com/versioneye/versioneye-core/files/399151/packages.txt) file (renamed to packages.txt for the sake of attaching to this issue), is showing all the dependencies as up to date:

![capture](https://cloud.githubusercontent.com/assets/5476382/17361687/9328986a-5969-11e6-82ad-4ca8c913cc16.PNG)

**Comment by timgluz** [comment]
Hi,

yes, it's because Nuget resolves these versions as "6.1.3 <= X", aka it limits only lowest limit but lefts upper limit open; if you want to limit upper limit, then you must specify "allowedVersions" attribute.

It's sounds bit strange to me, but that's what [Nuget documentation](https://docs.nuget.org/create/versioning#constraining-upgrades-to-allowed-versions) says about `packages.config`.

**Comment by reiz** [comment]
Hey @Nysosis it seems that @timgluz is right, that's I close this ticket. If you think this is still an issue, feel free to re open this ticket.

**Comment by Nysosis** [comment]
@timgluz @reiz 

I think that resolution logic is only when determining which version of the package to upgrade to, and not which version of the package to install when installing the packages.

If I delete all the contents of the installed packages folder, and do a nuget restore using the packages.config, then I will always get version 4.5.6 of Newtonsoft.Json.

If I then execute an Update-Package, Newtonsoft.Json will then get updated to the most recent version (currently) 9.0.1, because of the resolution logic specified in the documentation.

**Comment by timgluz** [comment]
ok, thanks for your feedback; 

I think install-resolution would be the correct way to approach then; and it'll be pretty simple fix;

I'll also try it out as soon as i can mono and nuget up and running on my OSx machine;

**Comment by timgluz** [comment]
Yes, `nuget install` will only install fixed versions, only `nuget update` will pull latest;

 i'll update NugetPackagesParsers accordingly.

**Comment by timgluz** [comment]
@nysosis, it's now using install resolution and most of dependenncies in your test project are now red;
