### ISSUE TITLE
Gemspec parser doesn't store unknown dependencies

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#47]
I uploaded the gemspec from this project to a VersionEye instance with an empty database. The file was parsed but the project had 0 dependencies. It seems the parser is not storing unknown dependencies.

**Comment by reiz** [comment]
The funny thing is that in the header it even says that there are 22 unknown dependencies. But they don't show up in the dependency table. 

![screen shot 2016-09-06 at 10 45 20](https://cloud.githubusercontent.com/assets/652130/18267504/a57740ae-741f-11e6-947b-73484c24b9c6.png)

**Comment by timgluz** [comment]
Interesting, is there any logs output related to this issue?

**Comment by reiz** [comment]
No. Nothing special in the logs.

**Comment by reiz** [comment]
@timgluz I deployed the parser to production. It works like charm if there are no unknown dependencies. 

![screen shot 2016-09-06 at 11 08 24](https://cloud.githubusercontent.com/assets/652130/18268051/64c69e9e-7422-11e6-9cd1-ee8ccea774c4.png)

**Comment by timgluz** [comment]
Ok, i will check into it - it probably misses some required field;
