### ISSUE TITLE
Unknown dependencies are displayed as up-to-date

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#50]
The gemspec parser now creates dependencies for unknown dependencies but they are makred as up-to-date. 

![screen shot 2016-09-06 at 17 20 38](https://cloud.githubusercontent.com/assets/652130/18279887/66db2166-7457-11e6-8c41-b7b3fa9cd78c.png)

As they are unknown we don't know if they are up-to-date or not. It should be marked in grey colour like here: 

![screen shot 2016-09-06 at 17 19 01](https://cloud.githubusercontent.com/assets/652130/18279908/8438cfec-7457-11e6-90e4-e9eb467a340b.png)

I think it's enough if the `projectdependency.prod_key` is set to `nil` for unknown dependencies, when it will be displayed as unknown in grey colour.

**Comment by reiz** [comment]
I just fixed it :)

**Comment by timgluz** [comment]
Did you updated ProjectService.outdated? function or just fixed that thing locally?  I'm afraid that other parsers may be affected by this issue. (i can't check your change on phone)
