### ISSUE TITLE
Support for yarn.lock

### ISSUE THREAD

**Issue by FaKeller** [versioneye/versioneye-core#57]
[yarn](https://yarnpkg.com/) is an alternative to `npm` and is gaining a lot of traction lately. During package installation, yarn [creates a `yarn.lock` file](https://yarnpkg.com/en/docs/yarn-lock) which stores the actual versions of the installed dependencies as resolved from the `package.json` file.

I'd love to see the lock file supported by VersionEye. Are there any plans to support yarn in the near future?

**Comment by reiz** [comment]
Hi @FaKeller today @timgluz finished the Yarn support. It's deployed to production. Would be great if you could test it and give us some feedback. Let us know if it works like expected. Would love to hear your feedback!

**Comment by FaKeller** [comment]
We are currently evaluating an on-premise installation of VersionEye. Are the changes already released to the latest Docker images?

**Comment by reiz** [comment]
@FaKeller Yes. All the changes are on Docker hub. Every time we do deployment to production the Docker images on Docker Hub are updated.

**Comment by reiz** [comment]
I close this ticket because it's implemented an deployed to production.
