### ISSUE TITLE
Packages.config parser not parsing versions correctly

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#58]
The .NET packages.config parser is not recognising the versions correctly. The versions in this file are all fixed: https://github.com/symphonyoss/RestApiClient/blob/master/test/SymphonyOSS.RestApiClient.Tests/packages.config. But somehow the result after parsing looks like this: 

![screen shot 2017-01-29 at 16 23 24](https://cloud.githubusercontent.com/assets/652130/22405222/9b57b170-e63f-11e6-8b00-8774c592711e.png)

Somehow the versions are in brackets and VersionEye can't find a match for them, that's why it's showed as unknown. But if you remove the brackets we have exact matches for them in our database and even the correct license ;-) /cc @timgluz

**Comment by timgluz** [comment]
I will check into tomorrow - seems Nuget has moved under Microsoft umbrella and some rules related to version specifier has changed/updated: https://docs.microsoft.com/en-us/nuget/create-packages/dependency-versions#version-ranges
