### ISSUE TITLE
Licenses are not fetched correctly fro CSharp projects

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#59]
A VersionEye project was created based on this file: https://github.com/symphonyoss/RestApiClient/blob/master/src/SymphonyOSS.RestApiClient/packages.config. Here is how it looks like: 

![screen shot 2017-01-29 at 16 54 29](https://cloud.githubusercontent.com/assets/652130/22405491/f196cef0-e643-11e6-80d9-c4df39bcb2f2.png)

On the screenshot the license is "Nuget unknown". Even after re parsing the project. But if you follow the package link to the Newtonsoft.Json page you can see that we actually have a license for exact that version. 

![screen shot 2017-01-29 at 16 54 51](https://cloud.githubusercontent.com/assets/652130/22405506/2379e8f8-e644-11e6-9691-494f0a423bfc.png)

For some dependencies the license is displayed correctly in the VersionEye project view, but for some not. Maybe it has something to do with case sensitive names or with version ranges. Please double check this.

**Comment by timgluz** [comment]
Oki-Doki!

**Comment by reiz** [comment]
This is fixed now. It was an issue with fetching the license names for the license cache.
