### ISSUE TITLE
add support for NPM5 package-lock.json

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye-core#79]
New NPM has new lock file: https://docs.npmjs.com/files/package-lock.json

**Comment by reiz** [comment]
@timgluz I have read about it. Should be similar to shrinkwrap. Work on this as next. That would be could content for our next newsletter ;-)

**Comment by timgluz** [comment]
It's done and cant be close

**Comment by reiz** [comment]
@timgluz Good Job!
