### ISSUE TITLE
Supported files for Node.JS

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#81]
Compile a list of all files which are supported for Node.JS developers. We need that for the next newsletter.

**Comment by timgluz** [comment]
Ok, i now have some details: `package.json`, `yarn.lock` & `npm-shrinkwrap.json` , i also add them to the `app/views/user/projects/helpers/_create_from_upload.html.erb` and `app/views/user/projects/helpers/_create_from_url.html.erb`

source: https://github.com/timgluz/versioneye-core/blob/a83c96271d92754529f588ddee154ff83b918c97/lib/versioneye/parsers/common_parser.rb#L155

**Comment by reiz** [comment]
@timgluz what about the new NPM lock file?

**Comment by timgluz** [comment]
It doesnt have parser yet.

**Comment by reiz** [comment]
@timgluz OK. We need to add a parser for `package-lock.json`. Like described here http://jpospisil.com/2017/06/02/understanding-lock-files-in-npm-5.html.

**Comment by reiz** [comment]
Supported files should be: 

 - package.json 
 - yarn.lock
 - npm-shrinkwrap.json
 - package-lock.json

**Comment by reiz** [comment]
Waiting until #79 is finished, then we can update the list on our pages and add it to the newsletter.

**Comment by timgluz** [comment]
Done!

**Comment by reiz** [comment]
Awesome :-)

**Comment by reiz** [comment]
Thanks. I put it into the next newsletter.
