### ISSUE TITLE
Add parsers for Golang's Dep pkg manager

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye-core#86]
It seems to be the official package manager for Golang and it'll be useful for `GodepsGithubCrawler`, which tries to read dependency details from commited project files.

Dependency files in the `Dep` are straightforward TOML files:

* Gopkg.toml 
* Gopkg.lock

here's their official repo: https://github.com/golang/dep

**Comment by timgluz** [comment]
Done, it is still in `add_glide_parser` branch and waiting experiment run of `GodepsGithubCrawler`

**Comment by reiz** [comment]
@timgluz I merged your PR. It's part of the core now.
