### ISSUE TITLE
Check why dependencies on Elixir/Phoenix page is still marked as outdated

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye-core#90]
All dependencies are here marked as outdated: https://www.versioneye.com/elixir/phoenix/1.2.4

Is is parser error or any worker is not fired?

**Comment by timgluz** [comment]
It was just missing 2 calls to CrawlerUtils

**Comment by reiz** [comment]
@timgluz It's still broken because this line [here](https://github.com/versioneye/versioneye-core/blob/88efa2d86ec565b79030673b646e493c6b063be7/lib/versioneye/services/dependency_service.rb#L106) always returns nil for Elixir packages. Can you double check and fix that please?

**Comment by timgluz** [comment]
Seems to fixed now
