### ISSUE TITLE
Parser for package-lock.json should support http deps

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#92]
The parser for `package-lock.json` should support http dependencies from NPMRegistry. 

![screen shot 2017-06-16 at 11 23 11](https://user-images.githubusercontent.com/652130/27220890-f3f7110a-5286-11e7-955e-9bbc57286754.png)

**Comment by timgluz** [comment]
Ok-doki

**Comment by reiz** [comment]
This seems to work. Customer is happy 👍
