### ISSUE TITLE
bower-asset support for PHP composer parser

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#95]
The composer parser should support bower-assets. Currently the bower dependencies are unknown. 

![screen shot 2017-06-19 at 16 14 07](https://user-images.githubusercontent.com/652130/27289508-77ef5974-550a-11e7-8ce2-fa10aae202ae.png)

**Comment by timgluz** [comment]
ok, i will update fetching products and will add couple of specs for that

**Comment by timgluz** [comment]
Interesting, it already has support for `npm-asset` and `bower-asset`

**Comment by timgluz** [comment]
Do you have copy of this project file? I cant replicate the issue;

**Comment by reiz** [comment]
Hi @timgluz it's this project here: https://github.com/phpffcms/ffcms/blob/master/composer.json.

**Comment by timgluz** [comment]
Just tested it with that project file and it works .

**Comment by reiz** [comment]
@timgluz OK. Did you test it with your versioneye-core code on localhost? Or on production VersionEye.com?

**Comment by timgluz** [comment]
Uploaded from URL to Says and it worked

**Comment by reiz** [comment]
Just tried my self. It works.
