### ISSUE TITLE
Improving .NET parsers

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#97]
There are some mistakes in the version of the library identified. For example, a csproj file contains this line:

```
<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="5.1.3" />
```

But the [report](https://www.versioneye.com/user/projects/59491e40368b08003e9b77af?child=summary) indicates version 5.1.4.

**Comment by timgluz** [comment]
Hmm, not sure it's bug;

According to Nuget specification version range `5.1.3`, translates to `>= 5.1.3` and for this package the `5.1.4` is the latest version;

**Comment by reiz** [comment]
@timgluz Thanks for the fast response. Let's keep this ticket open for discussion. I will send a link to the customer.

**Comment by michaelkruglos** [comment]
Actually, after checking it on my local machine, csproj seems to work differently.
I reported documentation bug to dotnet/docs project [here](https://github.com/dotnet/docs/issues/2461)

**Comment by timgluz** [comment]
Interesting, does `*.csproj` does even support version ranges? Only thing  i see it has a thing called `floating version`, which is wildcard selector;

**Comment by michaelkruglos** [comment]
The docs here say that it works like nuget: https://github.com/dotnet/docs/blob/master/docs/core/tools/csproj.md#version

**Comment by reiz** [comment]
@michaelkruglos Thanks for reporting the documentation bug. We adjust the parser.

**Comment by timgluz** [comment]
seems we got official response:

```
`Version` specifies the version of the package to restore. The attribute respects the rules of the [NuGet versioning](https://docs.microsoft.com/nuget/create-packages/dependency-versions#version-ranges) scheme. The default behavior is an exact version match. For example, specifying `Version="1.2.3"` is equivalent to NuGet notation `[1.2.3]` for the exact 1.2.3 version of the package.

```

i am going to update rules for `*.csproj` files.

**Comment by reiz** [comment]
Cool. That makes sense :-)

**Comment by timgluz** [comment]
CsProjParser translates now all the semver versions as nuget "[semver]" version range;

**Comment by reiz** [comment]
@timgluz @michaelkruglos I just merged the PR. Should go online with the next deployment. Last on Monday.

**Comment by reiz** [comment]
@timgluz @michaelkruglos This improvement is rolled out to production now.
